name: myat_ecommerence
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  badges: ^3.1.2
  cloud_firestore: ^5.4.4
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  expansion_tile_card: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  file_picker: ^8.0.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  photo_view: ^0.15.0
  device_info_plus: ^9.1.1
  permission_handler: ^11.3.1
  gallery_saver_plus: ^3.2.0
  google_fonts: ^6.2.1
  modal_bottom_sheet: ^3.0.0
  circular_image: ^0.0.6
  bot_toast: ^4.1.3





  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.4.1
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  getwidget: ^4.0.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  icons_launcher: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  showcaseview: ^3.0.0
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21