// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5E4uEp0E_7svv-G4jl7OHAuxFNXg33wY',
    appId: '1:191405085984:android:c8fb393753112ffcbcb345',
    messagingSenderId: '191405085984',
    projectId: 'myatecommerce',
    storageBucket: 'myatecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9njwNfnfuKv2Zo3sNk8iQW12TV0fQcio',
    appId: '1:191405085984:ios:42e01fd359506a54bcb345',
    messagingSenderId: '191405085984',
    projectId: 'myatecommerce',
    storageBucket: 'myatecommerce.firebasestorage.app',
    iosBundleId: 'app.com.mm.myatEcommerence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYjarDU9cjje70KLsz-YzRxq2BBSEqw_c',
    appId: '1:638749066043:web:d4754a64ffc7e3a7cced1e',
    messagingSenderId: '638749066043',
    projectId: 'taxiproj-b2f9d',
    authDomain: 'taxiproj-b2f9d.firebaseapp.com',
    storageBucket: 'taxiproj-b2f9d.appspot.com',
  );
}